### ISSUE TITLE
Convert to Spiff instead of SD

### ISSUE THREAD

**Issue by RobertHolscher** [G6EJD/ESP32-8266-File-Download#2]
Hi , I like your solution very much. I was thinking that maybe downloading from the Spiff in ESP is also a function which is possible with your solution. Have you thought of changing your code to support also SPiff ?

**Comment by G6EJD** [comment]
Yes, I’ve done this and been using a SPIFF version for over 18-months without any issues. All you need to do is remove the sd-card initialisation and replace with spiffs variants the rest of the code remains as is.
This is not really a code issue.

**Comment by RobertHolscher** [comment]
Thank you very much for the email

Can you share your code for it?

Kind regards

Robert 

Verstuurd vanaf mijn iPhone

Op 21 apr. 2019 om 23:57 heeft G6EJD <notifications@github.com> het volgende geschreven:

Yes, I’ve done this and been using a SPIFF version for over 18-months without any issues. All you need to do is remove the sd-card initialisation and replace with spiffs variants the rest of the code remains as is.
This is not really a code issue.

**Comment by G6EJD** [comment]
Uploaded a revised version for SPIFFS
