### ISSUE TITLE
 Empty file

### ISSUE THREAD

**Issue by DVB-Arduino** [G6EJD/ESP32-8266-File-Download#3]
When I connect to the ESP8266 directly without a router, the page loads, click download, enter the file name, but the file is downloaded empty. The file definitely exists, it is not empty. What could be the reason?

**Comment by G6EJD** [comment]
What is the file extension? And size?
Have you configured the ESP wifi to AP ( access point)? Have you tried a different file type and size say a small text file test.txt

**Comment by G6EJD** [comment]
Also you may need to downgrade the ide to 2.4.2 the last known working version

**Comment by DVB-Arduino** [comment]
In setup, I first create a file and write a “test” into it. Then your code is unchanged.

`
#ifdef ESP8266
#include <ESP8266WiFi.h>       // Built-in
#include <ESP8266WiFiMulti.h>  // Built-in
#include <ESP8266WebServer.h>  // Built-in
#include <ESP8266mDNS.h>
#include "FS.h"
#else
#include <WiFi.h>              // Built-in
#include <WiFiMulti.h>         // Built-in
#include <ESP32WebServer.h>    // https://github.com/Pedroalbuquerque/ESP32WebServer download and place in your Libraries folder
#include <ESPmDNS.h>
#include "FS.h"
#endif

#include "Network.h"
#include "Sys_Variables.h"
#include "CSS.h"
#include <SPI.h>

#ifdef ESP8266
ESP8266WiFiMulti wifiMulti;
ESP8266WebServer server(80);
#else
WiFiMulti wifiMulti;
ESP32WebServer server(80);
#endif


// File
const char* filename1 = "/data.csv";

//
void setup(void) {
Serial.begin(115200);
 // File System
  if (SPIFFS.begin())
  {
    Serial.println("SPIFFS Initialize....ok");
  }
  else
  {
    Serial.println("SPIFFS Initialization...failed");
  }
  if (SPIFFS.exists(filename1))
  {
    Serial.println("Файл существует");
  }
else
  {
    if (SPIFFS.format())
    {
      Serial.println("Файловая система отформатирована");
    }
    else
    {
      Serial.println("Ошибка форматирования файловой системы");
    }
File f = SPIFFS.open(filename1, "w");
if (!f)
    {
      Serial.println("Файл не открывается");
    }
else
    {
      Serial.println("Запись данных в файл");
      f.print("test");
     f.close();
    }
  }
if (!WiFi.config(local_IP, gateway, subnet, dns)) { //WiFi.config(ip, gateway, subnet, dns1, dns2);
    Serial.println("WiFi STATION Failed to configure Correctly");
  }
  wifiMulti.addAP(ssid_1, password_1);  // add Wi-Fi networks you want to connect to, it connects strongest to weakest
  wifiMulti.addAP(ssid_2, password_2);  // Adjust the values in the Network tab
  wifiMulti.addAP(ssid_3, password_3);
  wifiMulti.addAP(ssid_4, password_4);  // You don't need 4 entries, this is for example!

  Serial.println("Connecting ...");
  while (wifiMulti.run() != WL_CONNECTED) { // Wait for the Wi-Fi to connect: scan for Wi-Fi networks, and connect to the strongest of the networks above
    delay(250); Serial.print('.');
  }
  Serial.println("\nConnected to " + WiFi.SSID() + " Use IP address: " + WiFi.localIP().toString()); // Report which SSID and IP is in use
  // The logical name http://fileserver.local will also access the device if you have 'Bonjour' running or your system supports multicast dns
  if (!MDNS.begin(servername)) {          // Set your preferred server name, if you use "myserver" the address would be http://myserver.local/
    Serial.println(F("Error setting up MDNS responder!"));
    ESP.restart();
  }
#ifdef ESP32
  // Note: SD_Card readers on the ESP32 will NOT work unless there is a pull-up on MISO, either do this or wire one on (1K to 4K7)
  Serial.println(MISO);
  pinMode(19, INPUT_PULLUP);
#endif
  Serial.print(F("Initializing SD card..."));
  SPIFFS.begin();                           // Start the SPI Flash Files System
  // Note: Using the ESP32 and SD_Card readers requires a 1K to 4K7 pull-up to 3v3 on the MISO line, otherwise they do-not function.
  //----------------------------------------------------------------------
  ///////////////////////////// Server Commands
  server.on("/",         HomePage);
  server.on("/download", File_Download);
  ///////////////////////////// End of Request commands
  server.begin();
  Serial.println("HTTP server started");
}
//
void loop(void) {
  server.handleClient(); // Listen for client connections
}

// All supporting functions from here...
//
void HomePage() {
  SendHTML_Header();
  webpage += F("<a href='/download'><button>Download</button></a>");
  append_page_footer();
  SendHTML_Content();
  SendHTML_Stop(); // Stop is needed because no content length was sent
}
//
void File_Download() { // This gets called twice, the first pass selects the input, the second pass then processes the command line arguments
  if (server.args() > 0 ) { // Arguments were received
    if (server.hasArg("download")) SD_file_download(server.arg(0));
  }
  else SelectInput("File Download", "Enter filename to download", "download", "download");
}
//
void SD_file_download(String filename) {
  File download = SPIFFS.open("/" + filename, "r");
  if (download) {
    server.sendHeader("Content-Type", "text/text");
    server.sendHeader("Content-Disposition", "attachment; filename=" + filename);
    server.sendHeader("Connection", "close");
    server.streamFile(download, "application/octet-stream");
    download.close();
  } else ReportFileNotPresent("download");
}
//
void SendHTML_Header() {
  server.sendHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  server.sendHeader("Pragma", "no-cache");
  server.sendHeader("Expires", "-1");
  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.send(200, "text/html", ""); // Empty content inhibits Content-length header so we have to close the socket ourselves.
  append_page_header();
  server.sendContent(webpage);
  webpage = "";
}
//
void SendHTML_Content() {
  server.sendContent(webpage);
  webpage = "";
}
//
void SendHTML_Stop() {
  server.sendContent("");
  server.client().stop(); // Stop is needed because no content length was sent
}
//
void SelectInput(String heading1, String heading2, String command, String arg_calling_name) {
  SendHTML_Header();
  webpage += F("<h3 class='rcorners_m'>"); webpage += heading1 + "</h3><br>";
  webpage += F("<h3>"); webpage += heading2 + "</h3>";
  webpage += F("<FORM action='/"); webpage += command + "' method='post'>"; // Must match the calling argument e.g. '/chart' calls '/chart' after selection but with arguments!
  webpage += F("<input type='text' name='"); webpage += arg_calling_name; webpage += F("' value=''><br>");
  webpage += F("<type='submit' name='"); webpage += arg_calling_name; webpage += F("' value=''><br><br>");
  append_page_footer();
  SendHTML_Content();
  SendHTML_Stop();
}
//
void ReportFileNotPresent(String target) {
  SendHTML_Header();
  webpage += F("<h3>File does not exist</h3>");
  webpage += F("<a href='/"); webpage += target + "'>[Back]</a><br><br>";
  append_page_footer();
  SendHTML_Content();
  SendHTML_Stop();
} 
`

**Comment by DVB-Arduino** [comment]
Yes, it works differently on 2.4.2 than on 2.5.2. I saw this in terms of waiting for a connection. But I can’t check the connection yet, because there is no home router.
In my project, I need to connect directly to the ESP8266 from a smartphone and download the file. How can i do this?

**Comment by G6EJD** [comment]
The default WiFi connection is in STAtion mode and the setup needs to be changed to Access Point mode, which I don’t have time to do right now as I’m still recovering from blood cancer, is like to help further but the change required is already well documented in the Arduino community and that’s all that’s required to be done, the code is no different whether the connection is client-server as you need or client to client via a router.

**Comment by DVB-Arduino** [comment]
Thanks. Get well soon.
