### ISSUE TITLE
File on SPIFFS empty on file download

### ISSUE THREAD

**Issue by DaveBrad** [G6EJD/ESP32-8266-File-Download#4]
void SD_file_download(String filename) {
  File download = SPIFFS.open("/" + filename, "w");

Should the above by "'r" rather than "w"? I tried your program, but found the file on the ESP was empty (0 bytes) after doing the download.

I notice, 'download' and 'upload' are confusing terms when dealing with ESPs. Most google searches show up okay (up/down-load). but the ESP as ESP-server or ESP-client is unclear as to context for the most part.

In this case its ESP-server to download to client (client<-svr).

Just thought I'd let you know.

**Comment by G6EJD** [comment]
Well for the ESP examples the context is always from an ESP point of view / centric and in that regard the W is correct.  All the examples have been tested. So do you think this is an issue?

**Comment by DaveBrad** [comment]
Below is the full context of the code  in question (context for code at issue). Also code from ESP8266 user guide ( context ESP8266 user guide)

In both context  'server.streamFile' is being used. This is a send-to-server method.

One uses read (correct usage, I believe), the other write.

 File file = SPIFFS.open(path, "r");                 // Open it
    size_t sent = server.streamFile(file, contentType); // And send it to the client

versus:

File download = SPIFFS.open("/" + filename, "w");
  if (download) {
  ::::
    server.streamFile(download, "application/octet-stream");

In 'SD_file_download' the code is using server.sendHeader(xxxxxxxxxxxxxx.. This to me is a response header from  server-to-client as a download at the client (ESP->client upload). 

Having a "w" seems incorrect to "server.send".

The code below, will test and the download works. But:
- I found 0 bytes for client file just downloaded, and 
- when looking at the ESP file system the file had been overwritten to 0 bytes.



== context ESP8266 user guide

https://tttapa.github.io/ESP8266/Chap11%20-%20SPIFFS.html


bool handleFileRead(String path) { // send the right file to the client (if it exists)
  Serial.println("handleFileRead: " + path);
  if (path.endsWith("/")) path += "index.html";         // If a folder is requested, send the index file
  String contentType = getContentType(path);            // Get the MIME type
  if (SPIFFS.exists(path)) {                            // If the file exists
    File file = SPIFFS.open(path, "r");                 // Open it
    size_t sent = server.streamFile(file, contentType); // And send it to the client
    file.close();                                       // Then close the file again
    return true;
  }
  Serial.println("\tFile Not Found");
  return false;                                         // If the file doesn't exist, return false
}

== context for code at issue

void File_Download() { // This gets called twice, the first pass selects the input, the second pass then processes the command line arguments
  if (server.args() > 0 ) { // Arguments were received
    if (server.hasArg("download")) SD_file_download(server.arg(0));
  }
  else SelectInput("File Download", "Enter filename to download", "download", "download");
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
void SD_file_download(String filename) {
  File download = SPIFFS.open("/" + filename, "w");
  if (download) {
    server.sendHeader("Content-Type", "text/text");
    server.sendHeader("Content-Disposition", "attachment; filename=" + filename);
    server.sendHeader("Connection", "close");
    server.streamFile(download, "application/octet-stream");
    download.close();
  } else ReportFileNotPresent("download");
}

**Comment by G6EJD** [comment]
OK, thanks, I amended the code accordingly, don't know how this happens. I think when the SPIFFS version was added it came from the Download code but was not amended.

**Comment by DaveBrad** [comment]
Thank you
